### ISSUE TITLE
Hostile sender?

### ISSUE THREAD

**Issue by mark-i-m** [veorq/oee#15]
> OEE is secure against hostile endpoints, while end-to-end encryption is only secure against hostile networks

While this is pretty useful, what about hostile **startpoints**?

I propose a `-n` flag that toggles no-ended encryption.

**Comment by nonchip** [comment]
that's already implemented in another project even predating this one: `/bin/false`

**Comment by mark-i-m** [comment]
Ah, thanks!

Man, you should get a Turing Award!
