### ISSUE TITLE
How can I decrypt files?

### ISSUE THREAD

**Issue by haypo** [veorq/oee#18]
Hi,

Does someone have a contact at the NSA? I ran ooe in-place on all files of my hard drive and now my Linux doesn't boot anymore. Is there any known workaround? You know, backdoor, hardcoded secret key, something like that?

Can you at least decrypt my photos please?

Victor

**Comment by dune73** [comment]
Do you have bitcoins?

**Comment by basisbit** [comment]
decryption is not possible thanks to usage of one-end-encryption. This is as intended and also the biggest feature of this project.

**Comment by haypo** [comment]
I reinstalled my computer to fix the issue.

**Comment by basisbit** [comment]
would be great if you could reproduce the issue and make sure that "reinstalling the computer" works as temporary or permanent solution! Thanks in advance.
